from tkinter import *

screen = Tk()

screen.title("My List")
screen.geometry("300x400")
screen.config(background="red")

scroll_bar = Scrollbar(screen)
scroll_bar.pack(side=RIGHT, fill=Y)

list_store = Listbox(screen, width=25, height=10,
                     yscrollcommand=scroll_bar.set)

    
list_store.insert(1, "Pizza")
list_store.insert(2, "Burger")
list_store.insert(3, "Chicken")
list_store.insert(4, "Fries")
list_store.insert(5, "Rice")
list_store.insert(6, "Pasta")
list_store.insert(7, "Hotdog")
list_store.insert(8, "Sandwich")
list_store.insert(9, "Salad")
list_store.insert(10, "Fish")
list_store.insert(11, "Cake")
list_store.insert(12, "Ice Cream")
list_store.insert(13, "Chocolate")
list_store.insert(14, "Donut")
list_store.insert(15, "Apple")
list_store.insert(16, "Orange")
list_store.insert(17, "Banana")
list_store.insert(18, "Strawberry")
list_store.insert(19, "Watermelon")
list_store.insert(20, "Mango")

list_store.insert(21, "Pizza")
list_store.insert(22, "Burger")
list_store.insert(23, "Chicken")
list_store.insert(24, "Fries")
list_store.insert(25, "Rice")
list_store.insert(26, "Pasta")
list_store.insert(27, "Hotdog")
list_store.insert(28, "Sandwich")
list_store.insert(29, "Salad")
list_store.insert(30, "Fish")
list_store.insert(31, "Cake")
list_store.insert(32, "Ice Cream")
list_store.insert(33, "Chocolate")
list_store.insert(34, "Donut")
list_store.insert(35, "Apple")
list_store.insert(36, "Orange")
list_store.insert(37, "Banana")
list_store.insert(38, "Strawberry")
list_store.insert(39, "Watermelon")
list_store.insert(40, "Mango")

list_store.insert(41, "Pizza")
list_store.insert(42, "Burger")
list_store.insert(43, "Chicken")
list_store.insert(44, "Fries")
list_store.insert(45, "Rice")
list_store.insert(46, "Pasta")
list_store.insert(47, "Hotdog")
list_store.insert(48, "Sandwich")
list_store.insert(49, "Salad")
list_store.insert(50, "Fish")
list_store.insert(51, "Cake")
list_store.insert(52, "Ice Cream")
list_store.insert(53, "Chocolate")
list_store.insert(54, "Donut")
list_store.insert(55, "Apple")
list_store.insert(56, "Orange")
list_store.insert(57, "Banana")
list_store.insert(58, "Strawberry")
list_store.insert(59, "Watermelon")
list_store.insert(60, "Mango")

list_store.insert(61, "Pizza")
list_store.insert(62, "Burger")
list_store.insert(63, "Chicken")
list_store.insert(64, "Fries")
list_store.insert(65, "Rice")
list_store.insert(66, "Pasta")
list_store.insert(67, "Hotdog")
list_store.insert(68, "Sandwich")
list_store.insert(69, "Salad")
list_store.insert(70, "Fish")
list_store.insert(71, "Cake")
list_store.insert(72, "Ice Cream")
list_store.insert(73, "Chocolate")
list_store.insert(74, "Donut")
list_store.insert(75, "Apple")
list_store.insert(76, "Orange")
list_store.insert(77, "Banana")
list_store.insert(78, "Strawberry")
list_store.insert(79, "Watermelon")
list_store.insert(80, "Mango")

list_store.insert(81, "Pizza")
list_store.insert(82, "Burger")
list_store.insert(83, "Chicken")
list_store.insert(84, "Fries")
list_store.insert(85, "Rice")
list_store.insert(86, "Pasta")
list_store.insert(87, "Hotdog")
list_store.insert(88, "Sandwich")
list_store.insert(89, "Salad")
list_store.insert(90, "Fish")
list_store.insert(91, "Cake")
list_store.insert(92, "Ice Cream")
list_store.insert(93, "Chocolate")
list_store.insert(94, "Donut")
list_store.insert(95, "Apple")
list_store.insert(96, "Orange")
list_store.insert(97, "Banana")
list_store.insert(98, "Strawberry")
list_store.insert(99, "Watermelon")
list_store.insert(100, "Mango")

list_store.pack(side=LEFT, fill=BOTH)

scroll_bar.config(command=list_store.yview)

mainloop()